groups:
- name: /1/store/projects/vagrant/docker-swarm-vagrant/apps/swarmprom/prometheus/rules/swarm_node.rules.yml
  rules:
  # absent(((time() - container_last_seen{name=~"pihole_pihole.*"}) < 5))
  ##count(count(container_tasks_state{container_label_com_docker_swarm_node_id =~".+"}) by (container_label_com_docker_swarm_node_id)) < 3
  ##count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~".+"}) < 3
  - alert: piholeMissing
    expr: (count(time() - container_last_seen{name=~".*pihole_pihole.*"} < 30) OR vector(0)) < 2
    for: 30s
    labels:
      severity: error
    annotations:
      description: Less than 2 pihole containers exist!  Check status of home DNS setup!
      summary: pihole container missing
  - alert: less_than_6_nodes
    expr: count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~".+"}) < 6
    for: 5m
    labels:
      severity: error
    annotations:
      description: Number of Swarm nodes is less than 6, check setup to maintain cluster health.
      summary: Swarm node went down, check setup.
  - alert: less_than_3_swarm_managers
    expr: sum(swarm_node_manager) < 3
    for: 5m
    labels:
      severity: error
    annotations:
      description: Number of Swarm Manager Nodes is less than 3!!!  Check cluster to maintain a quorum!
      summary: Swarm Manager Node went down, check cluster health.
  - alert: node_cpu_usage
    expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[1m]) * ON(instance) GROUP_LEFT(node_name)
      node_meta * 100) BY (node_name)) > 75
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{ $labels.node_name }} CPU usage is at {{ humanize
        $value}}%.
      summary: CPU alert for Swarm node '{{ $labels.node_name }}'
  - alert: node_memory_usage
    expr: sum(((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)
      * ON(instance) GROUP_LEFT(node_name) node_meta * 100) BY (node_name) > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{ $labels.node_name }} memory usage is at {{ humanize
        $value}}%.
      summary: Memory alert for Swarm node '{{ $labels.node_name }}'
  - alert: node_disk_usage
    expr: ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"})
      * 100 / node_filesystem_size_bytes{mountpoint="/"}) * ON(instance) GROUP_LEFT(node_name)
      node_meta > 85
    for: 1m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{ $labels.node_name }} disk usage is at {{ humanize
        $value}}%.
      summary: Disk alert for Swarm node '{{ $labels.node_name }}'
  - alert: node_disk_fill_rate_6h
    expr: predict_linear(node_filesystem_free_bytes{mountpoint="/"}[1h], 6 * 3600) * ON(instance)
      GROUP_LEFT(node_name) node_meta < 0
    for: 1h
    labels:
      severity: critical
    annotations:
      description: Swarm node {{ $labels.node_name }} disk is going to fill up in
        6h.
      summary: Disk fill alert for Swarm node '{{ $labels.node_name }}'
