cluster.name: "docker-cluster"
network.host: 0.0.0.0
path.repo: ["/mnt/elasticsearch-snapshot"]
discovery.type: single-node

xpack.license.self_generated.type: basic
xpack.security.enabled: false
xpack.monitoring.collection.enabled: false
xpack.ml.enabled: false